Dont use logfile for test builds, that makes CI unnecessarily difficult
Signed-off-by: Andreas K. Hüttel <dilfridge@gentoo.org>

diff --git a/src/build_and_run_all_cli_tests b/src/build_and_run_all_cli_tests
--- a/src/build_and_run_all_cli_tests
+++ b/src/build_and_run_all_cli_tests
@@ -65,12 +65,6 @@ fi
 # option -fno-keep-inline-dllexport'
 PATH=/C/QtOpenSource/Qt5.5.1/Tools/mingw492_32/bin:$PATH
 
-# Logging
-LOGFILE="build_and_run_all_cli_tests.log"
-rm -rf $LOGFILE
-echo
-echo "Afterwards, check $LOGFILE to verify success"
-
 # Cleanup. We do not want to force complete rebuild for each test application since that takes VERY long
 rm .moc_test/* 2>/dev/null
 rm .objs_test/* 2>/dev/null
@@ -94,9 +88,8 @@ else
     do
         sed "s/TEST/$t/g" engauge_test_template.pro >engauge_test.pro
         qmake6 $CONFIGARGS engauge_test.pro
-        make -j4 all 2>>$LOGFILE >/dev/null || {
-            echo "FAIL   : Compilation error is described in build_and_run_all_cli_tests.log"
-            echo "         Testing will be stopped"
+        make -j4 all || {
+            echo "FAIL   : Compilation error, testing will be stopped"
             exit 1
         }
         # sed is used to add color to PASS and FAIL. 'Using QtTest' lines are dropped
